### ISSUE TITLE
unsafely changing function name

### ISSUE THREAD

**Issue by lncknight-next** [tencentyun/tls-sig-api-v2-php#10]
it is not safely to change function name directly for the same tag, please revise / backward compatible

https://github.com/tencentyun/tls-sig-api-v2-php/commit/6c28a86544641ac7c46fd2d0c6f5fd6149a7effc#diff-60ee403e43e0963ee56b56cedd3ec6635290e1728b3ba301d85e84ca1672c7ccR6

**Comment by supgeek-rod** [comment]
AWESOME
